### ISSUE TITLE
No where Does it Tell you how to remove this.

### ISSUE THREAD

**Issue by z0z0Official** [zer0TF/cute-comfy#1]
No where does it tell users that it is going to replace the ENTIRE CSS Template and make it impossible to get to the settings since there is no Gear Icon. If there was a gear Icon I would love to use it with the ability to resize The Action Box(The floating interface)

Please put clear details on what this product does down to the T. There is no documentation anywhere.
![Screenshot 2023-10-16 033335](https://github.com/zer0TF/cute-comfy/assets/124645295/db155598-4a27-4e21-8f04-fd54e5052dbd)

Please elaborate more on it's behavior as well as how it can be utilized.

**Comment by z0z0Official** [comment]
![Screenshot 2023-10-15 224230](https://github.com/zer0TF/cute-comfy/assets/124645295/23643bc3-ef29-4b90-97b1-3037beee8742)
![Screenshot 2023-10-15 224219](https://github.com/zer0TF/cute-comfy/assets/124645295/254e084a-dd3e-4084-8d19-c89ba066059e)
![Screenshot 2023-10-15 224213](https://github.com/zer0TF/cute-comfy/assets/124645295/5a852cc1-f1a6-4b70-b29f-3c2f7c981473)
This was no fun trying to remove it because when I uninstalled it is did not delete the folder that was made and put in another directory... (No indication about this doing that in your main documentation...)

**Comment by z0z0Official** [comment]
Great Idea, Please Add Cog for SETTINGS. Then MAYBE adjustable Main controls(opacity adjusting?), Maybe The ability to doc on the left/right/top/bottom? :) A bot could dream 🥇

**Comment by zer0TF** [comment]
Resolved. ✅
