### ISSUE TITLE
use WEB_DIRECTORY instead of copying js files.

### ISSUE THREAD

**Issue by ltdrdata** [zer0TF/cute-comfy#2]
https://github.com/ltdrdata/ComfyUI-Inspire-Pack/blob/52e4a93ed5931dcbd47e9d8982fcb1e9e7b8411c/__init__.py#L32

```
WEB_DIRECTORY = "./js"
__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS", "WEB_DIRECTORY"]
```

Using this method is necessary to ensure that no leftover clutter remains in the web directory when disabling and deleting.
Furthermore, when debugging, testing can be done conveniently with a single original instead of copies.

**Comment by zer0TF** [comment]
Didn't know this existed honestly! Documentation would be nice instead of having to sift through source code. 🙂 I was modeling my code off of the ComfyUI OpenPose Editor module which uses a similar technique.

I will try this method out!

**Comment by zer0TF** [comment]
Resolved. ✅ 

If anyone happened to install this prior to now, please manually delete `ComfyUI/web/extensions/cute-comfy/main.js` from your installation.
