### ISSUE TITLE
Feature Request: Display Image-Feed button from ComfyUI-Custom-Scripts

### ISSUE THREAD

**Issue by lichenophile** [zer0TF/cute-comfy#3]
Appreciate the new layout, not perfect yet, but close! 

I have one troublesome issue. Which is that the [Image-Feed option of ComfyUI-Custom-Scripts](https://github.com/pythongosssss/ComfyUI-Custom-Scripts#image-feed), when closed, usually has a button beside the cog settings menu to reopen it. As such, I can no longer regain access to that feature while using Cute Comfy ><

![257839373-f72991d8-6708-4fe3-a805-ad850175d044](https://github.com/zer0TF/cute-comfy/assets/67679349/f6228764-bb93-475d-b67d-4b65afa9d576)

[Link to what I assume is the associated button code](https://github.com/pythongosssss/ComfyUI-Custom-Scripts/blob/main/web/js/imageFeed.js#L212)

**Comment by zer0TF** [comment]
I will fix this soon! 👍

**Comment by zer0TF** [comment]
This is fixed - please update the extension via the ComfyUI Manager!
